/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '2/02/17 9:16' with Gradle 2.13
 *
 * @author mati, @date 2/02/17 9:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
