/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '12/01/17 9:21' with Gradle 2.13
 *
 * @author mati, @date 12/01/17 9:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
